### ISSUE TITLE
Remaing km shows wrong number

### ISSUE THREAD

**Issue by wolfallein** [maisi/M365-Power#4]
Hi!

First, thank you for your code. I really appreciate it. I downloaded the last source code version, and could compile with Android Studio. I did some cosmetic modifications in the .xml (just to make the background black), but I didn't understand the communication part.

I couldn't figure out why the remaining km shows a different value when compared to another app 12.3km X 5.3km (attached a comparison). 

I saw that the scooter also sends information about the trip time, uptime, total mileage, and a mileometer that can be reset. Could you tell me, if possible, how can I get such information on your app screen?

Best regards,
Joao Pereira
![screenshot_20180914-101325_m365 tools](https://user-images.githubusercontent.com/15076592/45545699-66048480-b81b-11e8-861f-007c36a68249.jpg)
![screenshot_20180914-101300_m365 power](https://user-images.githubusercontent.com/15076592/45545743-86344380-b81b-11e8-87e2-28ea874b5b73.jpg)

**Comment by maisi** [comment]
Hello,

the difference in remaining distance is because I'm using custom battery consumption values to calculate the distance instead of using the distance the scooter is sending. In your screenshot you can see that the scooter estimates a consumption of 263 mah/km (3241/12,3). From my experience this is the ideal case where you drive on a flat street without a lot of stop-and-go traffic using the stock firmware. That's why my app uses a default value of 600 mah/km which is the worst case I had when driving around. While 400 mah/km seems to be a good average value it depends on a lot of factors, wind speed, driver weight, speed(custom firmware), flatness of the terrain etc. You can change the value in the settings to a fixed value or use the average, which would be 321 mah/km in your case.

It's possible to add anything the scooter can transmit, the mileometer is a pure app feature I think. However I don't really care about total mileage or total uptime (could be an app feature too) but I might add the current trip time in addition to the already existing trip length. 

I haven't really worked on the app for a month because my scooter was broken (blown fuse), but I'll hopefully be able to get some work done soon.

BR
Martin
